# Generated by Django 5.2.8 on 2025-11-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('player1', models.CharField(blank=True, max_length=50, null=True)),
                ('player2', models.CharField(blank=True, max_length=50, null=True)),
                ('current_turn', models.CharField(blank=True, max_length=10, null=True)),
                ('player1_grid', models.JSONField(default=list)),
                ('player2_grid', models.JSONField(default=list)),
                ('rematch_votes', models.JSONField(default=list)),
            ],
        ),
    ]
